### ISSUE TITLE
Installing on a Pi instead of Docker?

### ISSUE THREAD

**Issue by kfp000** [flyitalyadsb/flarm-ogn-to-sbs#1]
Installation is very bare bone - is it possible to install without docker? To a raspberry for example?

**Comment by riccardosabatti** [comment]
Hi kfp000,

Apologies for the delayed response, and thank you for the pull request.

Yes, it's absolutely possible. Just run the following commands:

```
pip install -r requirements.txt
python main.py --listen-on 3024 --only-messages-with-icao
```

You can adjust the configuration options as needed.

I've also updated the README to include these instructions.

Thanks again for your contribution!
